version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
       - image: circleci/python:3.7

    working_directory: ~/xTmp/xDev/modules/CalculatorLibrary

    steps:
      - checkout
      - run
         name: install dependencies
            command:  |
               python3 -m venv venv
               . venv/bin/activate
               pip install -r requirements.txt
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
            name: run tests
            command:  |
               . venv/bin/activiate
               flake8 —exclude=venv* —statistics
               pytest -v —cov=calculator


  main:
    jobs:
      - build-and-test
