# Python CircleCI 2.0 configuration file
version: 2
jobs:
   build:
      docker:
         - image: circleci/python:3.8

      working_directory: ~/xTmp/xDev/modules/CalculatorLibrary

      steps:
         # Step 1: obtain repo from GitHub
         - checkout
         # Step 2: create virtual env and install dependencies
         - run:
            name: install dependencies
            command:  |
               python3.8 -m venv calculator
               . calculator/bin/activate
               pip install -r requirements.txt
         # Step3: run linter and tests
         - run:
            name: run tests
            command:  |
               . calculator/bin/activate
               # python3.8 -m flake8 *.py
               pytest --cov=test_calculator --cov=calculator ~/xTmp/xDev/modules/CalculatorLibrary
