version: 2.1

orbs:
  python: circleci/python:3.8

jobs:
  build-and-test:
    executor: python3.8
    working_directory: ~/xTmp/xDev/modules/CalculatorLibrary
    steps:
      - checkout


      - run:
          command: 
             python3 -m venv venv
             . venv/bin/activate
             pip install -r requirements.txt
          name: Create virtual environment
      - run:
         command:  |
               . venv/bin/activiate
               flake8 —exclude=venv* —statistics
               pytest -v —cov=calculator
         name: run tests
         

workflows:
  main:
    jobs:
      - build-and-test
