version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
<<<<<<< HEAD
  build-and-test:
    docker:
       - image: circleci/python:3.7

    working_directory: ~/xTmp/xDev/modules/CalculatorLibrary
=======
   build:
      docker:
         - image: circleci/python:3.8

      working_directory: ~/xTmp/xDev/modules/CalculatorLibrary
>>>>>>> ef32e391c024ad349300df883a8a90d0b560105c

    steps:
      - checkout
      - run
         name: install_dependencies
            command:  |
               python3.8 -m venv calculator
               . calculator/bin/activate
               pip install -r requirements.txt
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
            name: run tests
            command:  |
<<<<<<< HEAD
               . venv/bin/activiate
               flake8 —exclude=venv* —statistics
               pytest -v —cov=calculator

workflows:
   
=======
               . calculator/bin/activate
               # python3.8 -m flake8 *.py
               pytest --cov=test_calculator --cov=calculator ~/xTmp/xDev/modules/CalculatorLibrary
>>>>>>> ef32e391c024ad349300df883a8a90d0b560105c
